spring.application.name=gateway_for_project

server.port= 8081


spring.cloud.gateway.routes[0].id=forum-service
spring.cloud.gateway.routes[0].uri=http://localhost:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/**



spring.cloud.gateway.routes[1].id=annonce-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/**



spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials
spring.cloud.gateway.default-filters[1]=DedupeResponseHeader=Access-Control-Allow-Origin

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*




eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone= http://localhost:8070/eureka
spring.cloud.gateway.discovery.locator.enabled=true
logging.level.com.netflix.eureka=DEBUG

logging.level.org.springframework.cloud.gateway=DEBUG
